package frc.robot.superstructure;

public enum SuperstructureState {
  IDLE,
  INTAKING,
  EJECTING,
  STATIC_AIMING,
  STATIC_SHOOTING,
  MANUAL_AIMING,
  MANUAL_SHOOTING,
  PASS_AIMING,
  PASS_SHOOTING,
  TUNING_AIMING,
  TUNING_SHOOTING,
  WRIST_MANUAL,
  WRIST_SLOW_UP,
  WRIST_SLOW_UP_WAIT,
  WRIST_DOWN_NO_STALL,
  WRIST_GOOD_STOW,
  WRIST_FORCE_DOWN,
  WRIST_FORCE_DOWN_STEP_1,
  WRIST_FORCE_DOWN_STEP_2,
  WRIST_FORCE_DOWN_STEP_3,
  FAULTED
}
